### ISSUE TITLE
Error: Impossible package selection

### ISSUE THREAD

**Issue by Norbert-Rotorwerk** [openwrt/asu#1077]
after owut upgrade here are the output:

owut - OpenWrt Upgrade Tool 2024.10.27~8c7e42f0-r1 (/usr/bin/owut)
ASU-Server     https://sysupgrade.openwrt.org
Upstream       https://downloads.openwrt.org
Target         mediatek/filogic
Profile        openwrt_one
Package-arch   aarch64_cortex-a53
Root-FS-type   squashfs
Sys-type       sysupgrade
Version-from   SNAPSHOT r27935-bcd95cb9c4 (kernel 6.6.58)
Version-to     SNAPSHOT r28041-a7bc6bf7db (kernel 6.6.59)
Build-FS-type  squashfs
Build-at       2024-11-09T16:31:59Z (~18 hours ago)
Image-prefix   openwrt-mediatek-filogic-openwrt_one
Image-URL      https://downloads.openwrt.org/snapshots/targets/mediatek/filogic
Image-file     openwrt-mediatek-filogic-openwrt_one-squashfs-sysupgrade.itb
Installed      245 packages
Top-level      145 packages
Default         42 packages
User-installed 109 packages (top-level only)

Package version changes:
  base-files                          1630~bcd95cb9c4                            1630~a7bc6bf7db
  ddns-scripts                        2.8.2-r50                                  2.8.2-r51
  ddns-scripts-services               2.8.2-r50                                  2.8.2-r51
  kmod-crypto-acompress               6.6.58-r1                                  6.6.59-r1
  kmod-crypto-aead                    6.6.58-r1                                  6.6.59-r1
  kmod-crypto-authenc                 6.6.58-r1                                  6.6.59-r1
  kmod-crypto-ccm                     6.6.58-r1                                  6.6.59-r1
  kmod-crypto-crc32c                  6.6.58-r1                                  6.6.59-r1
  kmod-crypto-ctr                     6.6.58-r1                                  6.6.59-r1
  kmod-crypto-des                     6.6.58-r1                                  6.6.59-r1
  kmod-crypto-gf128                   6.6.58-r1                                  6.6.59-r1
  kmod-crypto-ghash                   6.6.58-r1                                  6.6.59-r1
  kmod-crypto-hmac                    6.6.58-r1                                  6.6.59-r1
  kmod-crypto-hw-safexcel             6.6.58-r1                                  6.6.59-r1
  kmod-crypto-manager                 6.6.58-r1                                  6.6.59-r1
  kmod-crypto-md5                     6.6.58-r1                                  6.6.59-r1
  kmod-crypto-seqiv                   6.6.58-r1                                  6.6.59-r1
  kmod-crypto-sha1                    6.6.58-r1                                  6.6.59-r1
  kmod-crypto-sha256                  6.6.58-r1                                  6.6.59-r1
  kmod-crypto-sha512                  6.6.58-r1                                  6.6.59-r1
  kmod-gpio-button-hotplug            6.6.58-r5                                  6.6.59-r5
  kmod-hwmon-core                     6.6.58-r1                                  6.6.59-r1
  kmod-i2c-core                       6.6.58-r1                                  6.6.59-r1
  kmod-leds-gpio                      6.6.58-r1                                  6.6.59-r1
  kmod-lib-crc-ccitt                  6.6.58-r1                                  6.6.59-r1
  kmod-lib-crc32c                     6.6.58-r1                                  6.6.59-r1
  kmod-lib-lzo                        6.6.58-r1                                  6.6.59-r1
  kmod-libphy                         6.6.58-r1                                  6.6.59-r1
  kmod-mac80211                       6.6.58.6.11.2-r1                           6.6.59.6.11.2-r1
  kmod-mt76-connac                    6.6.58.2024.10.11.1~ecca0e77-r1            6.6.59.2024.10.11.1~ecca0e77-r1
  kmod-mt76-core                      6.6.58.2024.10.11.1~ecca0e77-r1            6.6.59.2024.10.11.1~ecca0e77-r1
  kmod-mt7915e                        6.6.58.2024.10.11.1~ecca0e77-r1            6.6.59.2024.10.11.1~ecca0e77-r1
  kmod-mt7981-firmware                6.6.58.2024.10.11.1~ecca0e77-r1            6.6.59.2024.10.11.1~ecca0e77-r1
  kmod-nf-flow                        6.6.58-r1                                  6.6.59-r1
  kmod-nf-nat                         6.6.58-r1                                  6.6.59-r1
  kmod-nf-reject                      6.6.58-r1                                  6.6.59-r1
  kmod-nf-reject6                     6.6.58-r1                                  6.6.59-r1
  kmod-nfnetlink                      6.6.58-r1                                  6.6.59-r1
  kmod-nft-fib                        6.6.58-r1                                  6.6.59-r1
  kmod-nft-nat                        6.6.58-r1                                  6.6.59-r1
  kmod-nvme                           6.6.58-r1                                  6.6.59-r1
  kmod-phy-airoha-en8811h             6.6.58-r1                                  6.6.59-r1
  kmod-phy-aquantia                   6.6.58-r1                                  6.6.59-r1
  kmod-pppoe                          6.6.58-r1                                  6.6.59-r1
  kmod-pppox                          6.6.58-r1                                  6.6.59-r1
  kmod-rtc-pcf8563                    6.6.58-r1                                  6.6.59-r1
  kmod-thermal                        6.6.58-r1                                  6.6.59-r1
  kmod-tun                            6.6.58-r1                                  6.6.59-r1
  kmod-usb-core                       6.6.58-r1                                  6.6.59-r1
  kmod-usb-xhci-hcd                   6.6.58-r1                                  6.6.59-r1
  kmod-usb-xhci-mtk                   6.6.58-r1                                  6.6.59-r1
  kmod-usb3                           6.6.58-r1                                  6.6.59-r1
  luci                                24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-adblock                    24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-attendedsysupgrade         24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-ddns                       24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-firewall                   24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-openvpn                    24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-package-manager            24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-sqm                        24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-app-uhttpd                     24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-base                           24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-compat                         24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-adblock-de                24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-attendedsysupgrade-de     24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-base-de                   24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-ddns-de                   24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-openvpn-de                24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-package-manager-de        24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-sqm-de                    24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-i18n-uhttpd-de                 24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-lib-base                       24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-lib-ip                         24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-lib-jsonc                      24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-lib-nixio                      24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-lib-uqr                        24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-light                          24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-lua-runtime                    24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-mod-admin-full                 24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-mod-network                    24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-mod-status                     24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-mod-system                     24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-proto-ipv6                     24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-proto-ppp                      24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-proto-wireguard                24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-ssl                            24.312.02741~1de73e1                       24.314.61805~96fa870
  luci-theme-bootstrap                24.312.02741~1de73e1                       24.314.61805~96fa870
  netifd                              2024.10.06~3c6265fd-r1                     2024.11.08~34eb11eb-r1
88 packages are out-of-date

Default package analysis:
  Default                             Provided-by
  nftables                            nftables-json

There are currently package build failures for SNAPSHOT aarch64_cortex-a53:
  Feed: packages
    micropython-lib                   Sat Nov  9 18:51:12 2024 - not installed
  Feed: telephony
    freetdm                           Sat Nov  9 19:21:21 2024 - not installed
Failures don't affect this device, details at
  https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a53/

Request:
  Version r28041-a7bc6bf7db (kernel 6.6.59)
Request hash:
  a75b2e8edc55a982237f3801eb47e81a
--
Status:   Error: Impossible package selection
Progress:   0s total =   0s in queue +   0s in build

Build failed in   0s total =   0s in queue +   0s to build:
ASU server error =
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rq/worker.py", line 1573, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rq/job.py", line 1322, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rq/job.py", line 1356, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asu/build.py", line 231, in build
    report_error(job, "Impossible package selection")
  File "/app/asu/util.py", line 293, in report_error
    raise RuntimeError(msg)
RuntimeError: Impossible package selection

ASU server stderr =
Generate local signing keys...
Generate local certificate...
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/kmods/6.6.59-1-0561031e21f60f05c8f540bffb723036/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/kmods/6.6.59-1-0561031e21f60f05c8f540bffb723036/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
/builder/staging_dir/host/bin/opkg: the ``install'' command requires at least one argument
make[2]: *** [Makefile:224: package_install] Error 1
make[1]: *** [Makefile:165: _call_manifest] Error 2
make: *** [Makefile:339: manifest] Error 2

ERROR: Build failed with status 500
The above errors are often due to the upgrade server lagging behind the
build server, first suggestion is to wait a while and try again.

Regards
Norbert

**Comment by efahl** [comment]
That one is fixed.  Once the apk builds go through, we need to fix the missing package index on the upstream site and fix the ubus call on clients.  Could be a week or two before owut works again...

**Comment by lorand-horvath** [comment]
> Could be a week or two before owut works again...

@efahl Thanks for responding. I'm not using owut at the moment, but the firmware-selector site. Is that in the same situation as owut? Or can I expect it to get fixed quicker than 1-2 weeks?

**Comment by efahl** [comment]
FS doesn't rely on either of the two bugs I mentioned, so as soon as the apk builds are done, it should work.  That might take 3-4 days though, as it requires a phase1 rebuild of all the targets/subtargets/profiles and then all of the packages in phase2.
